channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal =5.2.4
  - python =3.6
  - rsem =1.3.2-0
  - samtools =1.9
  - git
  - fastqc
  - skewer
  - star =2.7.0f-0
  - bedtools
  - lastz #slncky
  - ucsc-liftover #slncky
  - bedops # slncky
  - numpy
  - pandas
  - biopython
  - bioconductor-dexseq
  - perl-statistics-descriptive
  - perl-array-utils
  - ucsc-gff3togenepred
  - cufflinks
  - numpy # velocyto
  - scipy
  - cython
  - numba
  - matplotlib
  - scikit-learn
  - h5py
  - click
  - R=3.5.1
  - rpy2=2.9.4
  - r-devtools=2.0.1
  - pip
